version: "3.9"
services:
  database:
    image: "mariadb:10.5"
    container_name: superhero-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: superhero
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - "3310:3306"
    networks:
      - superhero-net

networks:
  superhero-net: